version: '3.7'
services:
  postgres: 
    image: postgres:9.6
    networks: 
      - default_net
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes: 
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  airflow-webserver:
    image: docker-airflow-spark:1.10.7_3.0.1
    restart: always
    networks:
      - default_net
    depends_on: 
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__FERNET_KEY=DJtNfks8maRuxIoXHzYY_E8E4eNvSgsRCmCgcJ6_83I=
    volumes:
       - ../dags:/usr/local/airflow/dags
       - ../spark/sdg-tryout:/usr/local/spark/sdg-tryout
       - ../spark/resources:/usr/local/spark/resources
    ports:
       - "8282:8282"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  spark:
    image: docker.io/bitnami/spark:latest
    user: root
    hostname: spark
    networks: 
      - default_net
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes: 
      - ../spark/sdg-tryout:/usr/local/spark/sdg-tryout
      - ../spark/resources:/usr/local/spark/resources
    ports:
      - '8181:8080'
      - '7077:7077'
  spark-worker-1:
    image: docker.io/bitnami/spark:latest
    user: root
    networks:
      - default_net 
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes: 
      - ../spark/sdg-tryout:/usr/local/spark/sdg-tryout
      - ../spark/resources:/usr/local/spark/resources
  spark-worker-2:
    image: docker.io/bitnami/spark:latest
    user: root
    networks:
      - default_net
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes: 
      - ../spark/sdg-tryout:/usr/local/spark/sdg-tryout
      - ../spark/resources:/usr/local/spark/resources
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - default_net
  kafka:
    build: ./kafka-docker
    ports:
      - "9092"
    networks:
      - default_net
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default_net:
